;(let (variable declarations)
;...body...)
(let ((a 5)
      (b 6))
  (+ a b))

;(flet ((function_name(args)
;...function body...))
;...body)
(flet ((f(n)
         (+ n 10))
       (g(n)
         (- n 3)))
  (f 5))

;(labels ((function_name(args)
;...function body...))
;...body)
(labels((a(n)
         (+ n 5))
       (b(n)
         (+ (a n) 6)))
  (b 10))
